#include "commands/compare_pooled.h"
#include "commands/estimate_pooled.h"
#include "commands/estimate_individual.h"
#include "commands/estimate_fst.h"
#include "commands/read.h"
#include "commands/write.h"
