#include "pipe/pipe.h"
#include "pipe/key_defs.h"
#include "datatypes/locus.h"
#include "datatypes/allele.h"
#include "datatypes/genotype.h"
#include "datatypes/population.h"
#include "datatypes/quartet.h"
