kap<-read.csv("KAP.out")
bus<-read.csv("BUS1.out")
#sps<-read.csv("SPS_out_small.txt")
sps<-read.csv("SPS_out_4.csv")

pa<-read.csv("PA.out")

X=2.9
Y=6.3
mar=0.6
XLIM=c(-0.2, 0.2)

col2=rgb(1,0,0)
col3=rgb(1,0,0,0.1)
col4=rgb(1,0,0,0.1)
red=rgb(1.,0.8,0.8)
black=rgb(0.2,0.2,0.2)
red=rgb(1.,0.8,0.8)

Y1=c(-0.2, 0.6)
Y2=c(-0.2, 1.02)
PCH=20
LABSIZE=1.25

pdf("f.pdf", width=X, height=Y)
par(mar=c(4,4.5,0.25, 1) )
boxplot(cex.lab=LABSIZE, list(sps$fC[sps$line.A==0 & sps$min.1 > 2.5 ], kap$fC[kap$line.A==0 & kap$min.1 > 2.5], pa$fC[pa$line.A==0 & pa$min.1 > 2.5 ],  bus$fC[bus$line.A==0 & bus$min.1 > 2.5]), ylab=expression(paste("Inbreeding  ", italic(f) ) ), xlab="population", border="white", names=c("", "", "", ""), outline=FALSE, ylim=Y1 )
abline(h=0,col=black,lty=2)
abline(h=-0.05,col=red,lty=2)
stripchart(list(sps$fC[sps$line.A==0 & sps$min.1 > 2.5 ], kap$fC[kap$line.A==0 & kap$min.1 > 2.5 & kap$line.C!=91 & kap$line.C!=88 & kap$line.C!=92], pa$fC[pa$line.A==0 & pa$min.1 > 2.5 ], bus$fC[bus$line.A==0 & bus$min.1 > 2.5]), vertical=TRUE, pch=PCH, col=col2, method="jitter", add = TRUE )
boxplot(sps$fC[sps$line.A==0 & sps$min.1 > 2.5 ], kap$fC[kap$line.A==0 & kap$min.1 > 2.5], pa$fC[pa$line.A==0 & pa$min.1 > 2.5 ],  bus$fC[bus$line.A==0 & bus$min.1 > 2.5], names=c("SPS", "KAP", "PA", "BUS"), add=TRUE, outline=FALSE, las=3 )
abline(h=0.0,col=black,lty=2)
abline(h=0.125,col=black,lty=2)
abline(h=0.25,col=black,lty=2)
abline(h=0.5,col=black,lty=2)
dev.off()


pdf("r.pdf", width=X, height=Y)
par(mar=c(4,4.5,0.25, 1) )
boxplot(cex.lab=LABSIZE, list(sps$r[sps$min.1 > 2.5 ], kap$r[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], pa$r[pa$min.1 > 2.5 ],  bus$r[bus$min.1 > 2.5]), outline=FALSE, border="white", ylab=expression(paste("Coancestry ", italic(Theta) ) ), xlab="population", names=c("", "", "", ""), ylim=Y1 )
abline(h=-0.05,col=red,lty=2)
abline(h=0.0,col=black,lty=2)
abline(h=0.125,col=black,lty=2)
abline(h=0.25,col=black,lty=2)
abline(h=0.5,col=black,lty=2)
abline(h=1.0,col=black,lty=2)
stripchart(list(round(sps$r[sps$min.1 > 2.5 ], digits=3), round(kap$r[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3), round(pa$r[pa$min.1 > 2.5 ], digits=3),  round(bus$r[bus$min.1 > 2.5], digits=3) ), vertical=TRUE, pch=PCH, col=col4, method="stack", add = TRUE, offset=0.015 )
stripchart(list(round(sps$r[sps$min.1 > 2.5 ], digits=3), round(kap$r[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3), round(pa$r[pa$min.1 > 2.5 ], digits=3),  round(bus$r[bus$min.1 > 2.5], digits=3) ), vertical=TRUE, pch=PCH, col=col4, method="stack", add = TRUE, offset=-0.015 )
boxplot(list(sps$r[sps$min.1 > 2.5 ], kap$r[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], pa$r[pa$min.1 > 2.5 ],  bus$r[bus$min.1 > 2.5]), outline=FALSE, add=TRUE, names=c("SPS", "KAP", "PA", "BUS"), las=3)
dev.off()

pdf("sCA.pdf", width=X, height=Y)
par(mar=c(4,4.5,0.25, 1) )
boxplot(cex.lab=LABSIZE, list(sps$sCA[sps$min.1 > 2.5 ], kap$sCA[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], pa$sCA[pa$min.1 > 2.5 ],  bus$sCA[bus$min.1 > 2.5]), outline=FALSE, border="white", ylab=expression(paste("Inbred relatedness ", italic(gamma) ) ), xlab="population", names=c("", "", "", ""), ylim=Y1 )
abline(h=0.0,col=black,lty=2)
abline(h=0.125,col=black,lty=2)
abline(h=0.25,col=black,lty=2)
abline(h=0.5,col=black,lty=2)
abline(h=1.0,col=black,lty=2)
stripchart(list(round(sps$sCA[sps$min.1 > 2.5 ], digits=3), round(kap$sCA[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3), round(pa$sCA[pa$min.1 > 2.5 ], digits=3),  round(bus$sCA[bus$min.1 > 2.5], digits=3) ), vertical=TRUE, pch=PCH, col=col4, method="stack", add = TRUE, offset=0.005 )
stripchart(list(round(sps$sCA[sps$min.1 > 2.5 ], digits=3), round(kap$sCA[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3), round(pa$sCA[pa$min.1 > 2.5 ], digits=3),  round(bus$sCA[bus$min.1 > 2.5], digits=3) ), vertical=TRUE, pch=PCH, col=col4, method="stack", add = TRUE, offset=-0.005 )
boxplot(list(sps$sCA[sps$min.1 > 2.5 ], kap$sCA[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], pa$sCA[pa$min.1 > 2.5 ],  bus$sCA[bus$min.1 > 2.5]), outline=FALSE, add=TRUE, names=c("SPS", "KAP", "PA", "BUS"), las=3 )
dev.off()

pdf("z.pdf", width=X, height=Y)
par(mar=c(4,4.5,0.25, 1) )
q=list(sps$z1[sps$min.1 > 2.5 ]+sps$z2[sps$min.1 > 2.5 ], kap$z1[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92]+ kap$z2[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], pa$z1[pa$min.1 > 2.5 ]+pa$z2[pa$min.1 > 2.5 ],  bus$z1[bus$min.1 > 2.5]+bus$z2[bus$min.1 > 2.5] )
boxplot(cex.lab=LABSIZE, q, ylim=Y2, outline=FALSE, border="white", ylab=expression(paste("Zygosity ", italic(rho) ) ), xlab="population", names=c("", "", "", ""))
abline(h=0.0,col=black,lty=2)
abline(h=0.125,col=black,lty=2)
abline(h=0.25,col=black,lty=2)
abline(h=0.5,col=black,lty=2)
abline(h=1.0,col=black,lty=2)
q=list(round(sps$z1[sps$min.1 > 2.5 ]+sps$z2[sps$min.1 > 2.5 ], digits=3), round(kap$z1[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92]+ kap$z2[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3), round(pa$z1[pa$min.1 > 2.5 ]+pa$z2[pa$min.1 > 2.5 ], digits=3),  round(bus$z1[bus$min.1 > 2.5]+bus$z2[bus$min.1 > 2.5],digits=3) )
stripchart(q, vertical=TRUE, pch=PCH, col=col4, method="stack", add = TRUE, offset=0.015 )
stripchart(q, vertical=TRUE, pch=PCH, col=col4, method="stack", add = TRUE, offset=-0.015 )
boxplot(q, outline=FALSE, add=TRUE, names=c("SPS", "KAP", "PA", "BUS"), las=3 )
dev.off()

pdf("zygosity_correlation.pdf", width=X, height=Y)
q1=c(sps$z1[sps$min.1 > 2.5 ], kap$z1[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], pa$z1[pa$min.1 > 2.5 ],  bus$z1[bus$min.1 > 2.5])
q2=c(sps$z2[sps$min.1 > 2.5 ], kap$z2[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], pa$z2[pa$min.1 > 2.5 ],  bus$z2[bus$min.1 > 2.5])
plot(q2~q1, outline=FALSE, border="white", xlab=expression(italic(delta) ), xlim=XLIM,ylim=XLIM*5.0, ylab=expression(italic(Delta) ), pch=PCH )
dev.off()

pdf("r_nine.pdf", width=X, height=Y)

Akap<-read.csv("KAP1.csv")
Bkap<-read.csv("KAP2.csv")
Ckap<-read.csv("KAP3.csv")

q=list(Akap$r[Akap$min.1 > 2.5 & Akap$line.C!=88 & Akap$line.C!=91 & Akap$line.C!=92], Bkap$r[Bkap$min.1 > 2.5 & Bkap$line.C!=88 & Bkap$line.C!=91 & Bkap$line.C!=92], Ckap$r[Ckap$min.1 > 2.5 & Ckap$line.C!=88 & Ckap$line.C!=91 & Ckap$line.C!=92] )
boxplot(cex.lab=LABSIZE, q, ylim=c(-0.2, 0.2), outline=FALSE, border="white", ylab=expression(italic(Theta) ), xlab="population", names=c("", "", ""))
abline(h=-0.05,col=red,lty=2)
abline(h=0.0,col=black,lty=2)
abline(h=0.125,col=black,lty=2)
abline(h=0.25,col=black,lty=2)
abline(h=0.5,col=black,lty=2)
abline(h=1.0,col=black,lty=2)
q=list(round(Akap$r[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3), round(Bkap$r[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3), round(Ckap$r[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3) )
stripchart(q, vertical=TRUE, pch=PCH, col=col4, method="stack", add = TRUE, offset=0.03 )
stripchart(q, vertical=TRUE, pch=PCH, col=col4, method="stack", add = TRUE, offset=-0.03 )
boxplot(q, outline=FALSE, add=TRUE, names=c("A A", "A B", "B B"), las=3 )
dev.off()

pdf("r_half.pdf", width=X, height=Y)

Akap<-read.csv("KAP4.csv")
Bkap<-read.csv("KAP5.csv")
Ckap<-read.csv("KAP6.csv")

q=list(Akap$r[Akap$min.1 > 2.5 & Akap$line.C!=88 & Akap$line.C!=91 & Akap$line.C!=92], Bkap$r[Bkap$min.1 > 2.5 & Bkap$line.C!=88 & Bkap$line.C!=91 & Bkap$line.C!=92], Ckap$r[Ckap$min.1 > 2.5 & Ckap$line.C!=88 & Ckap$line.C!=91 & Ckap$line.C!=92] )
boxplot(cex.lab=LABSIZE, q, ylim=c(-0.2, 0.2), outline=FALSE, border="white", ylab=expression(italic(Theta) ), xlab="population", names=c("", "", ""))
abline(h=-0.05,col=red,lty=2)
abline(h=0.0,col=black,lty=2)
abline(h=0.125,col=black,lty=2)
abline(h=0.25,col=black,lty=2)
abline(h=0.5,col=black,lty=2)
abline(h=1.0,col=black,lty=2)
q=list(round(Akap$r[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3), round(Bkap$r[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3), round(Ckap$r[kap$min.1 > 2.5 & kap$line.C!=88 & kap$line.C!=91 & kap$line.C!=92], digits=3) )
stripchart(q, vertical=TRUE, pch=PCH, col=col4, method="stack", add = TRUE, offset=0.03 )
stripchart(q, vertical=TRUE, pch=PCH, col=col4, method="stack", add = TRUE, offset=-0.03 )
boxplot(q, outline=FALSE, add=TRUE, names=c("A A", "A B", "B B"), las=3 )
dev.off()
